<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class HadiahSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('hadiahs')->truncate();

        $now = now();
        
        DB::table('hadiahs')->insert([
            ['id_hadiah' => 1, 'id_lomba' => 1, 'posisi' => 'Diamond Medalist', 'nominal' => 'Unknown', 'deskripsi' => 'Uang Tunai, Plakat/Piala, Medali, Sertifikat, Beasiswa kelas Math Champs/Kalananti', 'created_at' => $now, 'updated_at' => $now],
            ['id_hadiah' => 2, 'id_lomba' => 1, 'posisi' => 'Gold Medalist', 'nominal' => '0', 'deskripsi' => 'Uang Tunai, Medali, Sertifikat, Voucher belajar kelas Math Champs/Kalananti', 'created_at' => $now, 'updated_at' => $now],
            ['id_hadiah' => 3, 'id_lomba' => 1, 'posisi' => 'Silver Medalist', 'nominal' => 'Unknown', 'deskripsi' => 'Uang Tunai, Medali, Sertifikat, Voucher belajar kelas Math Champs/Kalananti', 'created_at' => $now, 'updated_at' => $now],
            ['id_hadiah' => 4, 'id_lomba' => 1, 'posisi' => 'Bronze Medalist', 'nominal' => 'Unknown', 'deskripsi' => 'Uang Tunai, Medali, Sertifikat, Voucher belajar kelas Math Champs/Kalananti', 'created_at' => $now, 'updated_at' => $now],
            ['id_hadiah' => 20, 'id_lomba' => 13, 'posisi' => 'Winner', 'nominal' => '0', 'deskripsi' => 'Uang tunai + Piala + Sertifikat', 'created_at' => $now, 'updated_at' => $now],
            ['id_hadiah' => 21, 'id_lomba' => 13, 'posisi' => 'Runner Up', 'nominal' => '0', 'deskripsi' => 'Uang tunai + Piala + Sertifikat', 'created_at' => $now, 'updated_at' => $now],
            ['id_hadiah' => 22, 'id_lomba' => 13, 'posisi' => 'Juara 3', 'nominal' => '0', 'deskripsi' => 'Uang tunai + Piala + Sertifikat', 'created_at' => $now, 'updated_at' => $now],
            ['id_hadiah' => 23, 'id_lomba' => 14, 'posisi' => 'Winner', 'nominal' => '0', 'deskripsi' => 'Uang tunai + Piala + Sertifikat', 'created_at' => $now, 'updated_at' => $now],
            ['id_hadiah' => 24, 'id_lomba' => 14, 'posisi' => 'Runner Up', 'nominal' => '0', 'deskripsi' => 'Uang tunai + Piala + Sertifikat', 'created_at' => $now, 'updated_at' => $now],
            ['id_hadiah' => 25, 'id_lomba' => 14, 'posisi' => 'Juara 3', 'nominal' => '0', 'deskripsi' => 'Uang tunai + Piala + Sertifikat', 'created_at' => $now, 'updated_at' => $now],
            ['id_hadiah' => 26, 'id_lomba' => 15, 'posisi' => 'Winner', 'nominal' => '0', 'deskripsi' => 'Uang tunai + Piala + Sertifikat', 'created_at' => $now, 'updated_at' => $now],
            ['id_hadiah' => 27, 'id_lomba' => 15, 'posisi' => 'Runner Up', 'nominal' => '0', 'deskripsi' => 'Uang tunai + Piala + Sertifikat', 'created_at' => $now, 'updated_at' => $now],
            ['id_hadiah' => 28, 'id_lomba' => 15, 'posisi' => 'Juara 3', 'nominal' => '0', 'deskripsi' => 'Uang tunai + Piala + Sertifikat', 'created_at' => $now, 'updated_at' => $now],
            ['id_hadiah' => 29, 'id_lomba' => 16, 'posisi' => 'Winner', 'nominal' => '0', 'deskripsi' => 'Uang tunai + Piala + Sertifikat', 'created_at' => $now, 'updated_at' => $now],
            ['id_hadiah' => 30, 'id_lomba' => 16, 'posisi' => 'Runner Up', 'nominal' => '0', 'deskripsi' => 'Uang tunai + Piala + Sertifikat', 'created_at' => $now, 'updated_at' => $now],
            ['id_hadiah' => 31, 'id_lomba' => 16, 'posisi' => 'Juara 3', 'nominal' => '0', 'deskripsi' => 'Uang tunai + Piala + Sertifikat', 'created_at' => $now, 'updated_at' => $now],
            ['id_hadiah' => 32, 'id_lomba' => 17, 'posisi' => 'Winner', 'nominal' => '0', 'deskripsi' => 'Uang tunai + Piala + Sertifikat', 'created_at' => $now, 'updated_at' => $now],
            ['id_hadiah' => 33, 'id_lomba' => 17, 'posisi' => 'Runner Up', 'nominal' => '0', 'deskripsi' => 'Uang tunai + Piala + Sertifikat', 'created_at' => $now, 'updated_at' => $now],
            ['id_hadiah' => 34, 'id_lomba' => 17, 'posisi' => 'Juara 3', 'nominal' => '0', 'deskripsi' => 'Uang tunai + Piala + Sertifikat', 'created_at' => $now, 'updated_at' => $now],
            ['id_hadiah' => 35, 'id_lomba' => 18, 'posisi' => 'Winner', 'nominal' => '0', 'deskripsi' => 'Uang tunai + Piala + Sertifikat', 'created_at' => $now, 'updated_at' => $now],
            ['id_hadiah' => 36, 'id_lomba' => 18, 'posisi' => 'Runner Up', 'nominal' => '0', 'deskripsi' => 'Uang tunai + Piala + Sertifikat', 'created_at' => $now, 'updated_at' => $now],
            ['id_hadiah' => 37, 'id_lomba' => 18, 'posisi' => 'Juara 3', 'nominal' => '0', 'deskripsi' => 'Uang tunai + Piala + Sertifikat', 'created_at' => $now, 'updated_at' => $now],
            ['id_hadiah' => 38, 'id_lomba' => 19, 'posisi' => 'Winner', 'nominal' => '0', 'deskripsi' => 'Uang tunai + Piala + Sertifikat', 'created_at' => $now, 'updated_at' => $now],
            ['id_hadiah' => 39, 'id_lomba' => 19, 'posisi' => 'Runner Up', 'nominal' => '0', 'deskripsi' => 'Uang tunai + Piala + Sertifikat', 'created_at' => $now, 'updated_at' => $now],
            ['id_hadiah' => 40, 'id_lomba' => 19, 'posisi' => 'Juara 3', 'nominal' => '0', 'deskripsi' => 'Uang tunai + Piala + Sertifikat', 'created_at' => $now, 'updated_at' => $now],
            ['id_hadiah' => 41, 'id_lomba' => 20, 'posisi' => 'Winner', 'nominal' => '0', 'deskripsi' => 'Uang tunai + Piala + Sertifikat', 'created_at' => $now, 'updated_at' => $now],
            ['id_hadiah' => 42, 'id_lomba' => 20, 'posisi' => 'Runner Up', 'nominal' => '0', 'deskripsi' => 'Uang tunai + Piala + Sertifikat', 'created_at' => $now, 'updated_at' => $now],
            ['id_hadiah' => 43, 'id_lomba' => 20, 'posisi' => 'Juara 3', 'nominal' => '0', 'deskripsi' => 'Uang tunai + Piala + Sertifikat', 'created_at' => $now, 'updated_at' => $now],
            ['id_hadiah' => 44, 'id_lomba' => 21, 'posisi' => 'Winner', 'nominal' => '0', 'deskripsi' => 'Uang tunai + Piala + Sertifikat', 'created_at' => $now, 'updated_at' => $now],
            ['id_hadiah' => 45, 'id_lomba' => 21, 'posisi' => 'Runner Up', 'nominal' => '0', 'deskripsi' => 'Uang tunai + Piala + Sertifikat', 'created_at' => $now, 'updated_at' => $now],
            ['id_hadiah' => 46, 'id_lomba' => 21, 'posisi' => 'Juara 3', 'nominal' => '0', 'deskripsi' => 'Uang tunai + Piala + Sertifikat', 'created_at' => $now, 'updated_at' => $now],
            ['id_hadiah' => 47, 'id_lomba' => 22, 'posisi' => 'Winner', 'nominal' => '0', 'deskripsi' => 'Uang tunai + Piala + Sertifikat', 'created_at' => $now, 'updated_at' => $now],
            ['id_hadiah' => 48, 'id_lomba' => 22, 'posisi' => 'Runner Up', 'nominal' => '0', 'deskripsi' => 'Uang tunai + Piala + Sertifikat', 'created_at' => $now, 'updated_at' => $now],
            ['id_hadiah' => 49, 'id_lomba' => 22, 'posisi' => 'Juara 3', 'nominal' => '0', 'deskripsi' => 'Uang tunai + Piala + Sertifikat', 'created_at' => $now, 'updated_at' => $now],
            ['id_hadiah' => 50, 'id_lomba' => 23, 'posisi' => 'Winner', 'nominal' => '0', 'deskripsi' => 'Uang tunai + Piala + Sertifikat', 'created_at' => $now, 'updated_at' => $now],
            ['id_hadiah' => 51, 'id_lomba' => 23, 'posisi' => 'Runner Up', 'nominal' => '0', 'deskripsi' => 'Uang tunai + Piala + Sertifikat', 'created_at' => $now, 'updated_at' => $now],
            ['id_hadiah' => 52, 'id_lomba' => 23, 'posisi' => 'Juara 3', 'nominal' => '0', 'deskripsi' => 'Uang tunai + Piala + Sertifikat', 'created_at' => $now, 'updated_at' => $now],
            ['id_hadiah' => 53, 'id_lomba' => 24, 'posisi' => 'Winner', 'nominal' => '0', 'deskripsi' => 'Uang tunai + Piala + Sertifikat', 'created_at' => $now, 'updated_at' => $now],
            ['id_hadiah' => 54, 'id_lomba' => 24, 'posisi' => 'Runner Up', 'nominal' => '0', 'deskripsi' => 'Uang tunai + Piala + Sertifikat', 'created_at' => $now, 'updated_at' => $now],
            ['id_hadiah' => 55, 'id_lomba' => 24, 'posisi' => 'Juara 3', 'nominal' => '0', 'deskripsi' => 'Uang tunai + Piala + Sertifikat', 'created_at' => $now, 'updated_at' => $now],
            ['id_hadiah' => 56, 'id_lomba' => 25, 'posisi' => 'Winner', 'nominal' => '0', 'deskripsi' => 'Uang tunai + Piala + Sertifikat', 'created_at' => $now, 'updated_at' => $now],
            ['id_hadiah' => 57, 'id_lomba' => 25, 'posisi' => 'Runner Up', 'nominal' => '0', 'deskripsi' => 'Uang tunai + Piala + Sertifikat', 'created_at' => $now, 'updated_at' => $now],
            ['id_hadiah' => 58, 'id_lomba' => 25, 'posisi' => 'Juara 3', 'nominal' => '0', 'deskripsi' => 'Uang tunai + Piala + Sertifikat', 'created_at' => $now, 'updated_at' => $now],
            ['id_hadiah' => 59, 'id_lomba' => 26, 'posisi' => 'Winner', 'nominal' => '0', 'deskripsi' => 'Uang tunai + Piala + Sertifikat', 'created_at' => $now, 'updated_at' => $now],
            ['id_hadiah' => 60, 'id_lomba' => 26, 'posisi' => 'Runner Up', 'nominal' => '0', 'deskripsi' => 'Uang tunai + Piala + Sertifikat', 'created_at' => $now, 'updated_at' => $now],
            ['id_hadiah' => 61, 'id_lomba' => 26, 'posisi' => 'Juara 3', 'nominal' => '0', 'deskripsi' => 'Uang tunai + Piala + Sertifikat', 'created_at' => $now, 'updated_at' => $now],
            ['id_hadiah' => 62, 'id_lomba' => 27, 'posisi' => 'Winner', 'nominal' => '0', 'deskripsi' => 'Uang tunai + Piala + Sertifikat', 'created_at' => $now, 'updated_at' => $now],
            ['id_hadiah' => 63, 'id_lomba' => 27, 'posisi' => 'Runner Up', 'nominal' => '0', 'deskripsi' => 'Uang tunai + Piala + Sertifikat', 'created_at' => $now, 'updated_at' => $now],
            ['id_hadiah' => 64, 'id_lomba' => 27, 'posisi' => 'Juara 3', 'nominal' => '0', 'deskripsi' => 'Uang tunai + Piala + Sertifikat', 'created_at' => $now, 'updated_at' => $now],
            ['id_hadiah' => 65, 'id_lomba' => 28, 'posisi' => 'Winner', 'nominal' => '0', 'deskripsi' => 'Uang tunai + Piala + Sertifikat', 'created_at' => $now, 'updated_at' => $now],
            ['id_hadiah' => 66, 'id_lomba' => 28, 'posisi' => 'Runner Up', 'nominal' => '0', 'deskripsi' => 'Uang tunai + Piala + Sertifikat', 'created_at' => $now, 'updated_at' => $now],
            ['id_hadiah' => 67, 'id_lomba' => 28, 'posisi' => 'Juara 3', 'nominal' => '0', 'deskripsi' => 'Uang tunai + Piala + Sertifikat', 'created_at' => $now, 'updated_at' => $now],
            ['id_hadiah' => 68, 'id_lomba' => 29, 'posisi' => 'Winner', 'nominal' => '0', 'deskripsi' => 'Uang tunai + Piala + Sertifikat', 'created_at' => $now, 'updated_at' => $now],
            ['id_hadiah' => 69, 'id_lomba' => 29, 'posisi' => 'Runner Up', 'nominal' => '0', 'deskripsi' => 'Uang tunai + Piala + Sertifikat', 'created_at' => $now, 'updated_at' => $now],
            ['id_hadiah' => 70, 'id_lomba' => 29, 'posisi' => 'Juara 3', 'nominal' => '0', 'deskripsi' => 'Uang tunai + Piala + Sertifikat', 'created_at' => $now, 'updated_at' => $now],
            ['id_hadiah' => 71, 'id_lomba' => 30, 'posisi' => 'Winner', 'nominal' => '0', 'deskripsi' => 'Uang tunai + Piala + Sertifikat', 'created_at' => $now, 'updated_at' => $now],
            ['id_hadiah' => 72, 'id_lomba' => 30, 'posisi' => 'Runner Up', 'nominal' => '0', 'deskripsi' => 'Uang tunai + Piala + Sertifikat', 'created_at' => $now, 'updated_at' => $now],
            ['id_hadiah' => 73, 'id_lomba' => 30, 'posisi' => 'Juara 3', 'nominal' => '0', 'deskripsi' => 'Uang tunai + Piala + Sertifikat', 'created_at' => $now, 'updated_at' => $now],
            ['id_hadiah' => 74, 'id_lomba' => 31, 'posisi' => 'Winner', 'nominal' => '0', 'deskripsi' => 'Uang tunai + Piala + Sertifikat', 'created_at' => $now, 'updated_at' => $now],
            ['id_hadiah' => 75, 'id_lomba' => 31, 'posisi' => 'Runner Up', 'nominal' => '0', 'deskripsi' => 'Uang tunai + Piala + Sertifikat', 'created_at' => $now, 'updated_at' => $now],
            ['id_hadiah' => 76, 'id_lomba' => 31, 'posisi' => 'Juara 3', 'nominal' => '0', 'deskripsi' => 'Uang tunai + Piala + Sertifikat', 'created_at' => $now, 'updated_at' => $now],
            ['id_hadiah' => 77, 'id_lomba' => 32, 'posisi' => 'Winner', 'nominal' => '0', 'deskripsi' => 'Uang tunai + Piala + Sertifikat', 'created_at' => $now, 'updated_at' => $now],
            ['id_hadiah' => 78, 'id_lomba' => 32, 'posisi' => 'Runner Up', 'nominal' => '0', 'deskripsi' => 'Uang tunai + Piala + Sertifikat', 'created_at' => $now, 'updated_at' => $now],
            ['id_hadiah' => 79, 'id_lomba' => 32, 'posisi' => 'Juara 3', 'nominal' => '0', 'deskripsi' => 'Uang tunai + Piala + Sertifikat', 'created_at' => $now, 'updated_at' => $now],
            ['id_hadiah' => 80, 'id_lomba' => 33, 'posisi' => 'Winner', 'nominal' => '0', 'deskripsi' => 'Uang tunai + Piala + Sertifikat', 'created_at' => $now, 'updated_at' => $now],
            ['id_hadiah' => 81, 'id_lomba' => 33, 'posisi' => 'Runner Up', 'nominal' => '0', 'deskripsi' => 'Uang tunai + Piala + Sertifikat', 'created_at' => $now, 'updated_at' => $now],
            ['id_hadiah' => 82, 'id_lomba' => 33, 'posisi' => 'Juara 3', 'nominal' => '0', 'deskripsi' => 'Uang tunai + Piala + Sertifikat', 'created_at' => $now, 'updated_at' => $now],
            ['id_hadiah' => 83, 'id_lomba' => 34, 'posisi' => 'Winner', 'nominal' => '0', 'deskripsi' => 'Uang tunai + Piala + Sertifikat', 'created_at' => $now, 'updated_at' => $now],
            ['id_hadiah' => 84, 'id_lomba' => 34, 'posisi' => 'Runner Up', 'nominal' => '0', 'deskripsi' => 'Uang tunai + Piala + Sertifikat', 'created_at' => $now, 'updated_at' => $now],
            ['id_hadiah' => 85, 'id_lomba' => 34, 'posisi' => 'Juara 3', 'nominal' => '0', 'deskripsi' => 'Uang tunai + Piala + Sertifikat', 'created_at' => $now, 'updated_at' => $now],
            ['id_hadiah' => 86, 'id_lomba' => 35, 'posisi' => 'Winner', 'nominal' => '0', 'deskripsi' => 'Uang tunai + Piala + Sertifikat', 'created_at' => $now, 'updated_at' => $now],
            ['id_hadiah' => 87, 'id_lomba' => 35, 'posisi' => 'Runner Up', 'nominal' => '0', 'deskripsi' => 'Uang tunai + Piala + Sertifikat', 'created_at' => $now, 'updated_at' => $now],
            ['id_hadiah' => 88, 'id_lomba' => 35, 'posisi' => 'Juara 3', 'nominal' => '0', 'deskripsi' => 'Uang tunai + Piala + Sertifikat', 'created_at' => $now, 'updated_at' => $now],
            ['id_hadiah' => 89, 'id_lomba' => 36, 'posisi' => 'Winner', 'nominal' => '0', 'deskripsi' => 'Uang tunai + Piala + Sertifikat', 'created_at' => $now, 'updated_at' => $now],
            ['id_hadiah' => 90, 'id_lomba' => 36, 'posisi' => 'Runner Up', 'nominal' => '0', 'deskripsi' => 'Uang tunai + Piala + Sertifikat', 'created_at' => $now, 'updated_at' => $now],
            ['id_hadiah' => 91, 'id_lomba' => 36, 'posisi' => 'Juara 3', 'nominal' => '0', 'deskripsi' => 'Uang tunai + Piala + Sertifikat', 'created_at' => $now, 'updated_at' => $now],
            ['id_hadiah' => 92, 'id_lomba' => 37, 'posisi' => 'Winner', 'nominal' => '0', 'deskripsi' => 'Uang tunai + Piala + Sertifikat', 'created_at' => $now, 'updated_at' => $now],
            ['id_hadiah' => 93, 'id_lomba' => 37, 'posisi' => 'Runner Up', 'nominal' => '0', 'deskripsi' => 'Uang tunai + Piala + Sertifikat', 'created_at' => $now, 'updated_at' => $now],
            ['id_hadiah' => 94, 'id_lomba' => 37, 'posisi' => 'Juara 3', 'nominal' => '0', 'deskripsi' => 'Uang tunai + Piala + Sertifikat', 'created_at' => $now, 'updated_at' => $now],
            ['id_hadiah' => 95, 'id_lomba' => 38, 'posisi' => 'Winner', 'nominal' => '0', 'deskripsi' => 'Uang tunai + Piala + Sertifikat', 'created_at' => $now, 'updated_at' => $now],
            ['id_hadiah' => 96, 'id_lomba' => 38, 'posisi' => 'Runner Up', 'nominal' => '0', 'deskripsi' => 'Uang tunai + Piala + Sertifikat', 'created_at' => $now, 'updated_at' => $now],
            ['id_hadiah' => 97, 'id_lomba' => 38, 'posisi' => 'Juara 3', 'nominal' => '0', 'deskripsi' => 'Uang tunai + Piala + Sertifikat', 'created_at' => $now, 'updated_at' => $now],
            ['id_hadiah' => 98, 'id_lomba' => 39, 'posisi' => 'Winner', 'nominal' => '0', 'deskripsi' => 'Uang tunai + Piala + Sertifikat', 'created_at' => $now, 'updated_at' => $now],
            ['id_hadiah' => 99, 'id_lomba' => 39, 'posisi' => 'Runner Up', 'nominal' => '0', 'deskripsi' => 'Uang tunai + Piala + Sertifikat', 'created_at' => $now, 'updated_at' => $now],
            ['id_hadiah' => 100, 'id_lomba' => 39, 'posisi' => 'Juara 3', 'nominal' => '0', 'deskripsi' => 'Uang tunai + Piala + Sertifikat', 'created_at' => $now, 'updated_at' => $now],
            ['id_hadiah' => 101, 'id_lomba' => 40, 'posisi' => 'Winner', 'nominal' => '0', 'deskripsi' => 'Uang tunai + Piala + Sertifikat', 'created_at' => $now, 'updated_at' => $now],
            ['id_hadiah' => 102, 'id_lomba' => 40, 'posisi' => 'Runner Up', 'nominal' => '0', 'deskripsi' => 'Uang tunai + Piala + Sertifikat', 'created_at' => $now, 'updated_at' => $now],
            ['id_hadiah' => 103, 'id_lomba' => 40, 'posisi' => 'Juara 3', 'nominal' => '0', 'deskripsi' => 'Uang tunai + Piala + Sertifikat', 'created_at' => $now, 'updated_at' => $now],
            ['id_hadiah' => 104, 'id_lomba' => 41, 'posisi' => 'Winner', 'nominal' => '0', 'deskripsi' => 'Uang tunai + Piala + Sertifikat', 'created_at' => $now, 'updated_at' => $now],
            ['id_hadiah' => 105, 'id_lomba' => 41, 'posisi' => 'Runner Up', 'nominal' => '0', 'deskripsi' => 'Uang tunai + Piala + Sertifikat', 'created_at' => $now, 'updated_at' => $now],
            ['id_hadiah' => 106, 'id_lomba' => 41, 'posisi' => 'Juara 3', 'nominal' => '0', 'deskripsi' => 'Uang tunai + Piala + Sertifikat', 'created_at' => $now, 'updated_at' => $now],
            ['id_hadiah' => 107, 'id_lomba' => 42, 'posisi' => 'Winner', 'nominal' => '0', 'deskripsi' => 'Uang tunai + Piala + Sertifikat', 'created_at' => $now, 'updated_at' => $now],
            ['id_hadiah' => 108, 'id_lomba' => 42, 'posisi' => 'Runner Up', 'nominal' => '0', 'deskripsi' => 'Uang tunai + Piala + Sertifikat', 'created_at' => $now, 'updated_at' => $now],
            ['id_hadiah' => 109, 'id_lomba' => 42, 'posisi' => 'Juara 3', 'nominal' => '0', 'deskripsi' => 'Uang tunai + Piala + Sertifikat', 'created_at' => $now, 'updated_at' => $now],
            ['id_hadiah' => 110, 'id_lomba' => 43, 'posisi' => 'Winner', 'nominal' => '0', 'deskripsi' => 'Uang tunai + Piala + Sertifikat', 'created_at' => $now, 'updated_at' => $now],
            ['id_hadiah' => 111, 'id_lomba' => 43, 'posisi' => 'Runner Up', 'nominal' => '0', 'deskripsi' => 'Uang tunai + Piala + Sertifikat', 'created_at' => $now, 'updated_at' => $now],
            ['id_hadiah' => 112, 'id_lomba' => 43, 'posisi' => 'Juara 3', 'nominal' => '0', 'deskripsi' => 'Uang tunai + Piala + Sertifikat', 'created_at' => $now, 'updated_at' => $now],
            ['id_hadiah' => 113, 'id_lomba' => 44, 'posisi' => 'Winner', 'nominal' => '0', 'deskripsi' => 'Uang tunai + Piala + Sertifikat', 'created_at' => $now, 'updated_at' => $now],
            ['id_hadiah' => 114, 'id_lomba' => 44, 'posisi' => 'Runner Up', 'nominal' => '0', 'deskripsi' => 'Uang tunai + Piala + Sertifikat', 'created_at' => $now, 'updated_at' => $now],
            ['id_hadiah' => 115, 'id_lomba' => 44, 'posisi' => 'Juara 3', 'nominal' => '0', 'deskripsi' => 'Uang tunai + Piala + Sertifikat', 'created_at' => $now, 'updated_at' => $now],
            ['id_hadiah' => 116, 'id_lomba' => 45, 'posisi' => 'Winner', 'nominal' => '0', 'deskripsi' => 'Uang tunai + Piala + Sertifikat', 'created_at' => $now, 'updated_at' => $now],
            ['id_hadiah' => 117, 'id_lomba' => 45, 'posisi' => 'Runner Up', 'nominal' => '0', 'deskripsi' => 'Uang tunai + Piala + Sertifikat', 'created_at' => $now, 'updated_at' => $now],
            ['id_hadiah' => 118, 'id_lomba' => 45, 'posisi' => 'Juara 3', 'nominal' => '0', 'deskripsi' => 'Uang tunai + Piala + Sertifikat', 'created_at' => $now, 'updated_at' => $now],
            ['id_hadiah' => 119, 'id_lomba' => 46, 'posisi' => 'Winner', 'nominal' => '0', 'deskripsi' => 'Uang tunai + Piala + Sertifikat', 'created_at' => $now, 'updated_at' => $now],
            ['id_hadiah' => 120, 'id_lomba' => 46, 'posisi' => 'Runner Up', 'nominal' => '0', 'deskripsi' => 'Uang tunai + Piala + Sertifikat', 'created_at' => $now, 'updated_at' => $now],
            ['id_hadiah' => 121, 'id_lomba' => 46, 'posisi' => 'Juara 3', 'nominal' => '0', 'deskripsi' => 'Uang tunai + Piala + Sertifikat', 'created_at' => $now, 'updated_at' => $now],
            ['id_hadiah' => 122, 'id_lomba' => 47, 'posisi' => 'Winner', 'nominal' => '0', 'deskripsi' => 'Uang tunai + Piala + Sertifikat', 'created_at' => $now, 'updated_at' => $now],
            ['id_hadiah' => 123, 'id_lomba' => 47, 'posisi' => 'Runner Up', 'nominal' => '0', 'deskripsi' => 'Uang tunai + Piala + Sertifikat', 'created_at' => $now, 'updated_at' => $now],
            ['id_hadiah' => 124, 'id_lomba' => 47, 'posisi' => 'Juara 3', 'nominal' => '0', 'deskripsi' => 'Uang tunai + Piala + Sertifikat', 'created_at' => $now, 'updated_at' => $now],
            ['id_hadiah' => 125, 'id_lomba' => 48, 'posisi' => 'Winner', 'nominal' => '0', 'deskripsi' => 'Uang tunai + Piala + Sertifikat', 'created_at' => $now, 'updated_at' => $now],
            ['id_hadiah' => 126, 'id_lomba' => 48, 'posisi' => 'Runner Up', 'nominal' => '0', 'deskripsi' => 'Uang tunai + Piala + Sertifikat', 'created_at' => $now, 'updated_at' => $now],
            ['id_hadiah' => 127, 'id_lomba' => 48, 'posisi' => 'Juara 3', 'nominal' => '0', 'deskripsi' => 'Uang tunai + Piala + Sertifikat', 'created_at' => $now, 'updated_at' => $now],
            ['id_hadiah' => 128, 'id_lomba' => 49, 'posisi' => 'Winner', 'nominal' => '0', 'deskripsi' => 'Uang tunai + Piala + Sertifikat', 'created_at' => $now, 'updated_at' => $now],
            ['id_hadiah' => 129, 'id_lomba' => 49, 'posisi' => 'Runner Up', 'nominal' => '0', 'deskripsi' => 'Uang tunai + Piala + Sertifikat', 'created_at' => $now, 'updated_at' => $now],
            ['id_hadiah' => 130, 'id_lomba' => 49, 'posisi' => 'Juara 3', 'nominal' => '0', 'deskripsi' => 'Uang tunai + Piala + Sertifikat', 'created_at' => $now, 'updated_at' => $now],
            ['id_hadiah' => 131, 'id_lomba' => 50, 'posisi' => 'Winner', 'nominal' => '0', 'deskripsi' => 'Uang tunai + Piala + Sertifikat', 'created_at' => $now, 'updated_at' => $now],
            ['id_hadiah' => 132, 'id_lomba' => 50, 'posisi' => 'Runner Up', 'nominal' => '0', 'deskripsi' => 'Uang tunai + Piala + Sertifikat', 'created_at' => $now, 'updated_at' => $now],
            ['id_hadiah' => 133, 'id_lomba' => 50, 'posisi' => 'Juara 3', 'nominal' => '0', 'deskripsi' => 'Uang tunai + Piala + Sertifikat', 'created_at' => $now, 'updated_at' => $now],
            ['id_hadiah' => 134, 'id_lomba' => 51, 'posisi' => 'Winner', 'nominal' => '0', 'deskripsi' => 'Uang tunai + Piala + Sertifikat', 'created_at' => $now, 'updated_at' => $now],
            ['id_hadiah' => 135, 'id_lomba' => 51, 'posisi' => 'Runner Up', 'nominal' => '0', 'deskripsi' => 'Uang tunai + Piala + Sertifikat', 'created_at' => $now, 'updated_at' => $now],
            ['id_hadiah' => 136, 'id_lomba' => 51, 'posisi' => 'Juara 3', 'nominal' => '0', 'deskripsi' => 'Uang tunai + Piala + Sertifikat', 'created_at' => $now, 'updated_at' => $now],
            ['id_hadiah' => 137, 'id_lomba' => 52, 'posisi' => 'Winner', 'nominal' => '0', 'deskripsi' => 'Uang tunai + Piala + Sertifikat', 'created_at' => $now, 'updated_at' => $now],
            ['id_hadiah' => 138, 'id_lomba' => 52, 'posisi' => 'Runner Up', 'nominal' => '0', 'deskripsi' => 'Uang tunai + Piala + Sertifikat', 'created_at' => $now, 'updated_at' => $now],
            ['id_hadiah' => 139, 'id_lomba' => 52, 'posisi' => 'Juara 3', 'nominal' => '0', 'deskripsi' => 'Uang tunai + Piala + Sertifikat', 'created_at' => $now, 'updated_at' => $now],
            ['id_hadiah' => 140, 'id_lomba' => 53, 'posisi' => 'Winner', 'nominal' => '0', 'deskripsi' => 'Uang tunai + Piala + Sertifikat', 'created_at' => $now, 'updated_at' => $now],
            ['id_hadiah' => 141, 'id_lomba' => 53, 'posisi' => 'Runner Up', 'nominal' => '0', 'deskripsi' => 'Uang tunai + Piala + Sertifikat', 'created_at' => $now, 'updated_at' => $now],
            ['id_hadiah' => 142, 'id_lomba' => 53, 'posisi' => 'Juara 3', 'nominal' => '0', 'deskripsi' => 'Uang tunai + Piala + Sertifikat', 'created_at' => $now, 'updated_at' => $now],
            ['id_hadiah' => 143, 'id_lomba' => 54, 'posisi' => 'Winner', 'nominal' => '0', 'deskripsi' => 'Uang tunai + Piala + Sertifikat', 'created_at' => $now, 'updated_at' => $now],
            ['id_hadiah' => 144, 'id_lomba' => 54, 'posisi' => 'Runner Up', 'nominal' => '0', 'deskripsi' => 'Uang tunai + Piala + Sertifikat', 'created_at' => $now, 'updated_at' => $now],
            ['id_hadiah' => 145, 'id_lomba' => 54, 'posisi' => 'Juara 3', 'nominal' => '0', 'deskripsi' => 'Uang tunai + Piala + Sertifikat', 'created_at' => $now, 'updated_at' => $now],
            ['id_hadiah' => 146, 'id_lomba' => 55, 'posisi' => 'Winner', 'nominal' => '0', 'deskripsi' => 'Uang tunai + Piala + Sertifikat', 'created_at' => $now, 'updated_at' => $now],
            ['id_hadiah' => 147, 'id_lomba' => 55, 'posisi' => 'Runner Up', 'nominal' => '0', 'deskripsi' => 'Uang tunai + Piala + Sertifikat', 'created_at' => $now, 'updated_at' => $now],
            ['id_hadiah' => 148, 'id_lomba' => 55, 'posisi' => 'Juara 3', 'nominal' => '0', 'deskripsi' => 'Uang tunai + Piala + Sertifikat', 'created_at' => $now, 'updated_at' => $now],
            ['id_hadiah' => 149, 'id_lomba' => 56, 'posisi' => 'Winner', 'nominal' => '0', 'deskripsi' => 'Uang tunai + Piala + Sertifikat', 'created_at' => $now, 'updated_at' => $now],
            ['id_hadiah' => 150, 'id_lomba' => 56, 'posisi' => 'Runner Up', 'nominal' => '0', 'deskripsi' => 'Uang tunai + Piala + Sertifikat', 'created_at' => $now, 'updated_at' => $now],
            ['id_hadiah' => 151, 'id_lomba' => 56, 'posisi' => 'Juara 3', 'nominal' => '0', 'deskripsi' => 'Uang tunai + Piala + Sertifikat', 'created_at' => $now, 'updated_at' => $now]
        ]);
    }
}