<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class LombaSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('lombas')->truncate();

        $now = now();
        
        DB::table('lombas')->insert([
            ['id_lomba' => 1, 'nama_lomba' => 'Ruangguru Mathematics and Logic Championship (RMC) 2025', 'deskripsi' => 'Lomba Matematika untuk TK-SD dari Ruangguru!', 'tgl_lomba' => '2025-05-26', 'lokasi' => 'Offline', 'link_daftar' => 'https://www.ruangguru.com/event/kompetisi-matematika', 'gambar' => 'uploads/1750083607_ruangguru-mathematics-and-logic-championship-rmc-2025-1.jpeg', 'penyelenggara_lomba' => 'Kalananti dan Math Champs by Ruangguru', 'updated_at' => $now, 'status' => 'available', 'id_bidang' => 14, 'kategori_peserta' => 'SD', 'created_at' => $now],
            ['id_lomba' => 13, 'nama_lomba' => 'ECODAYS 2025', 'deskripsi' => 'OPEN REGISTRATION – ECODAYS 2025 untuk kompetisi essay dan car development', 'tgl_lomba' => '2025-05-29', 'lokasi' => 'Online & Offline', 'link_daftar' => 'https://linktr.ee/ecodaysuns', 'gambar' => 'uploads/1750085330_ecodays-2025-0.png', 'penyelenggara_lomba' => 'HMTK FT UNS', 'updated_at' => $now, 'status' => 'available', 'id_bidang' => 59, 'kategori_peserta' => 'Mahasiswa', 'created_at' => $now],
            ['id_lomba' => 14, 'nama_lomba' => 'Lomba Cipta Puisi', 'deskripsi' => 'Lomba cipta puisi tingkat nasional untuk semua kalangan', 'tgl_lomba' => '2025-06-01', 'lokasi' => 'Online', 'link_daftar' => 'https://example.com/puisi', 'gambar' => 'uploads/1750083607_puisi.jpeg', 'penyelenggara_lomba' => 'Pena Kencana', 'updated_at' => $now, 'status' => 'available', 'id_bidang' => 17, 'kategori_peserta' => 'Umum', 'created_at' => $now],
            ['id_lomba' => 15, 'nama_lomba' => 'Lomba Desain Grafis', 'deskripsi' => 'Tunjukkan kreativitasmu dalam lomba desain grafis tingkat nasional', 'tgl_lomba' => '2025-06-10', 'lokasi' => 'Online', 'link_daftar' => 'https://example.com/desain-grafis', 'gambar' => 'uploads/1750083607_desain-grafis.jpeg', 'penyelenggara_lomba' => 'Dinas Pariwisata', 'updated_at' => $now, 'status' => 'available', 'id_bidang' => 18, 'kategori_peserta' => 'Umum', 'created_at' => $now],
            ['id_lomba' => 16, 'nama_lomba' => 'Lomba Karya Tulis Ilmiah', 'deskripsi' => 'Ajang bergengsi bagi para penulis ilmiah muda Indonesia', 'tgl_lomba' => '2025-06-15', 'lokasi' => 'Offline', 'link_daftar' => 'https://example.com/karya-tulis', 'gambar' => 'uploads/1750083607_karya-tulis.jpeg', 'penyelenggara_lomba' => 'Lembaga Penelitian', 'updated_at' => $now, 'status' => 'available', 'id_bidang' => 33, 'kategori_peserta' => 'Mahasiswa', 'created_at' => $now],
            ['id_lomba' => 17, 'nama_lomba' => 'Lomba Robotika', 'deskripsi' => 'Kembangkan robot terbaikmu dan menangkan hadiahnya!', 'tgl_lomba' => '2025-07-20', 'lokasi' => 'Offline', 'link_daftar' => 'https://example.com/robotika', 'gambar' => 'uploads/1750083607_robotika.jpeg', 'penyelenggara_lomba' => 'Robotika Indonesia', 'updated_at' => $now, 'status' => 'available', 'id_bidang' => 21, 'kategori_peserta' => 'Umum', 'created_at' => $now],
            ['id_lomba' => 18, 'nama_lomba' => 'Lomba Debat Bahasa Inggris', 'deskripsi' => 'Uji kemampuan berbahasa Inggrismu dalam lomba debat internasional', 'tgl_lomba' => '2025-08-05', 'lokasi' => 'Online', 'link_daftar' => 'https://example.com/debat-inggris', 'gambar' => 'uploads/1750083607_debat-inggris.jpeg', 'penyelenggara_lomba' => 'English Club', 'updated_at' => $now, 'status' => 'available', 'id_bidang' => 28, 'kategori_peserta' => 'Pelajar', 'created_at' => $now],
            ['id_lomba' => 19, 'nama_lomba' => 'Lomba Tari Tradisional', 'deskripsi' => 'Tampilkan bakat menarimu dalam lomba tari tradisional nusantara', 'tgl_lomba' => '2025-08-20', 'lokasi' => 'Offline', 'link_daftar' => 'https://example.com/tari-tradisional', 'gambar' => 'uploads/1750083607_tari-tradisional.jpeg', 'penyelenggara_lomba' => 'Seni Budaya', 'updated_at' => $now, 'status' => 'available', 'id_bidang' => 27, 'kategori_peserta' => 'Umum', 'created_at' => $now],
            ['id_lomba' => 20, 'nama_lomba' => 'Lomba Musik Akustik', 'deskripsi' => 'Buktikan kemampuan musik akustikmu dalam lomba bergengsi ini', 'tgl_lomba' => '2025-09-10', 'lokasi' => 'Online', 'link_daftar' => 'https://example.com/musik-akustik', 'gambar' => 'uploads/1750083607_musik-akustik.jpeg', 'penyelenggara_lomba' => 'Music Society', 'updated_at' => $now, 'status' => 'available', 'id_bidang' => 26, 'kategori_peserta' => 'Umum', 'created_at' => $now],
            ['id_lomba' => 21, 'nama_lomba' => 'Lomba Fotografi', 'deskripsi' => 'Abadikan momen terbaikmu dan menangkan hadiahnya!', 'tgl_lomba' => '2025-09-15', 'lokasi' => 'Online', 'link_daftar' => 'https://example.com/fotografi', 'gambar' => 'uploads/1750083607_fotografi.jpeg', 'penyelenggara_lomba' => 'Fotografi Club', 'updated_at' => $now, 'status' => 'available', 'id_bidang' => 19, 'kategori_peserta' => 'Umum', 'created_at' => $now],
            ['id_lomba' => 22, 'nama_lomba' => 'Lomba Video Kreatif', 'deskripsi' => 'Buat video kreatif terbaikmu dan raih hadiahnya!', 'tgl_lomba' => '2025-10-01', 'lokasi' => 'Online', 'link_daftar' => 'https://example.com/video-kreatif', 'gambar' => 'uploads/1750083607_video-kreatif.jpeg', 'penyelenggara_lomba' => 'Video Maker Society', 'updated_at' => $now, 'status' => 'available', 'id_bidang' => 60, 'kategori_peserta' => 'Umum', 'created_at' => $now],
            ['id_lomba' => 23, 'nama_lomba' => 'Lomba Blogging', 'deskripsi' => 'Tunjukkan kemampuan menulismu dalam lomba blogging tingkat nasional', 'tgl_lomba' => '2025-10-15', 'lokasi' => 'Online', 'link_daftar' => 'https://example.com/blogging', 'gambar' => 'uploads/1750083607_blog.jpeg', 'penyelenggara_lomba' => 'Blogging Community', 'updated_at' => $now, 'status' => 'available', 'id_bidang' => 65, 'kategori_peserta' => 'Umum', 'created_at' => $now],
            ['id_lomba' => 24, 'nama_lomba' => 'Lomba Desain Interior', 'deskripsi' => 'Ciptakan desain interior impianmu dalam lomba bergengsi ini', 'tgl_lomba' => '2025-11-01', 'lokasi' => 'Offline', 'link_daftar' => 'https://example.com/desain-interior', 'gambar' => 'uploads/1750083607_desain-interior.jpeg', 'penyelenggara_lomba' => 'Interior Design Institute', 'updated_at' => $now, 'status' => 'available', 'id_bidang' => 60, 'kategori_peserta' => 'Umum', 'created_at' => $now],
            ['id_lomba' => 25, 'nama_lomba' => 'Lomba Arsitektur', 'deskripsi' => 'Rancang bangun arsitektur terbaikmu dan menangkan hadiahnya!', 'tgl_lomba' => '2025-11-15', 'lokasi' => 'Offline', 'link_daftar' => 'https://example.com/arsitektur', 'gambar' => 'uploads/1750083607_arsitektur.jpeg', 'penyelenggara_lomba' => 'Arsitektur Indonesia', 'updated_at' => $now, 'status' => 'available', 'id_bidang' => 18, 'kategori_peserta' => 'Umum', 'created_at' => $now],
            ['id_lomba' => 26, 'nama_lomba' => 'Lomba Penelitian Siswa', 'deskripsi' => 'Kembangkan penelitian terbaikmu dan raih prestasi!', 'tgl_lomba' => '2025-12-01', 'lokasi' => 'Offline', 'link_daftar' => 'https://example.com/penelitian-siswa', 'gambar' => 'uploads/1750083607_penelitian-siswa.jpeg', 'penyelenggara_lomba' => 'Pusat Penelitian', 'updated_at' => $now, 'status' => 'available', 'id_bidang' => 32, 'kategori_peserta' => 'Pelajar', 'created_at' => $now],
            ['id_lomba' => 27, 'nama_lomba' => 'Lomba Karya Seni Rupa', 'deskripsi' => 'Tunjukkan bakat senimu dalam lomba karya seni rupa tingkat nasional', 'tgl_lomba' => '2025-12-15', 'lokasi' => 'Offline', 'link_daftar' => 'https://example.com/karya-seni-rupa', 'gambar' => 'uploads/1750083607_karya-seni-rupa.jpeg', 'penyelenggara_lomba' => 'Seni Rupa Indonesia', 'updated_at' => $now, 'status' => 'available', 'id_bidang' => 12, 'kategori_peserta' => 'Umum', 'created_at' => $now],
            ['id_lomba' => 28, 'nama_lomba' => 'Lomba Kaligrafi', 'deskripsi' => 'Tunjukkan keindahan kaligrafi dalam lomba bergengsi ini', 'tgl_lomba' => '2026-01-10', 'lokasi' => 'Offline', 'link_daftar' => 'https://example.com/kaligrafi', 'gambar' => 'uploads/1750083607_kaligrafi.jpeg', 'penyelenggara_lomba' => 'Kaligrafi Center', 'updated_at' => $now, 'status' => 'available', 'id_bidang' => 12, 'kategori_peserta' => 'Umum', 'created_at' => $now],
            ['id_lomba' => 29, 'nama_lomba' => 'Lomba Pidato', 'deskripsi' => 'Uji kemampuan public speakingmu dalam lomba pidato nasional', 'tgl_lomba' => '2026-01-20', 'lokasi' => 'Online', 'link_daftar' => 'https://example.com/pidato', 'gambar' => 'uploads/1750083607_pidato.jpeg', 'penyelenggara_lomba' => 'Public Speaking Academy', 'updated_at' => $now, 'status' => 'available', 'id_bidang' => 25, 'kategori_peserta' => 'Pelajar', 'created_at' => $now],
            ['id_lomba' => 30, 'nama_lomba' => 'Lomba Cipta Lagu', 'deskripsi' => 'Ciptakan lagu terbaikmu dan menangkan hadiahnya!', 'tgl_lomba' => '2026-02-10', 'lokasi' => 'Online', 'link_daftar' => 'https://example.com/cipta-lagu', 'gambar' => 'uploads/1750083607_cipta-lagu.jpeg', 'penyelenggara_lomba' => 'Music Creator Society', 'updated_at' => $now, 'status' => 'available', 'id_bidang' => 26, 'kategori_peserta' => 'Umum', 'created_at' => $now],
            ['id_lomba' => 31, 'nama_lomba' => 'Lomba Menulis Cerita Pendek', 'deskripsi' => 'Tunjukkan kemampuan menulismu dalam lomba cerita pendek nasional', 'tgl_lomba' => '2026-02-20', 'lokasi' => 'Online', 'link_daftar' => 'https://example.com/cerita-pendek', 'gambar' => 'uploads/1750083607_cerita-pendek.jpeg', 'penyelenggara_lomba' => 'Short Story Community', 'updated_at' => $now, 'status' => 'available', 'id_bidang' => 17, 'kategori_peserta' => 'Umum', 'created_at' => $now],
            ['id_lomba' => 32, 'nama_lomba' => 'Lomba Desain Fashion', 'deskripsi' => 'Ciptakan desain fashion terbaikmu dalam lomba bergengsi ini', 'tgl_lomba' => '2026-03-10', 'lokasi' => 'Offline', 'link_daftar' => 'https://example.com/desain-fashion', 'gambar' => 'uploads/1750083607_desain-fashion.jpeg', 'penyelenggara_lomba' => 'Fashion Institute', 'updated_at' => $now, 'status' => 'available', 'id_bidang' => 18, 'kategori_peserta' => 'Umum', 'created_at' => $now],
            ['id_lomba' => 33, 'nama_lomba' => 'Lomba Makeup Artistry', 'deskripsi' => 'Tunjukkan keahlian makeup mu dalam lomba nasional ini', 'tgl_lomba' => '2026-03-20', 'lokasi' => 'Offline', 'link_daftar' => 'https://example.com/makeup-artistry', 'gambar' => 'uploads/1750083607_makeup-artistry.jpeg', 'penyelenggara_lomba' => 'Beauty School', 'updated_at' => $now, 'status' => 'available', 'id_bidang' => 12, 'kategori_peserta' => 'Umum', 'created_at' => $now],
            ['id_lomba' => 34, 'nama_lomba' => 'Lomba Hairstyling', 'deskripsi' => 'Ciptakan gaya rambut terbaikmu dalam lomba bergengsi ini', 'tgl_lomba' => '2026-04-10', 'lokasi' => 'Offline', 'link_daftar' => 'https://example.com/hairstyling', 'gambar' => 'uploads/1750083607_hairstyling.jpeg', 'penyelenggara_lomba' => 'Hair Fashion Academy', 'updated_at' => $now, 'status' => 'available', 'id_bidang' => 12, 'kategori_peserta' => 'Umum', 'created_at' => $now],
            ['id_lomba' => 35, 'nama_lomba' => 'Lomba Seni Lukis', 'deskripsi' => 'Tunjukkan bakat melukismu dalam lomba seni lukis nasional', 'tgl_lomba' => '2026-04-20', 'lokasi' => 'Offline', 'link_daftar' => 'https://example.com/seni-lukis', 'gambar' => 'uploads/1750083607_seni-lukis.jpeg', 'penyelenggara_lomba' => 'Painting Community', 'updated_at' => $now, 'status' => 'available', 'id_bidang' => 12, 'kategori_peserta' => 'Umum', 'created_at' => $now],
            ['id_lomba' => 36, 'nama_lomba' => 'Lomba Kaligrafi Modern', 'deskripsi' => 'Gabungkan seni kaligrafi dan modernitas dalam lomba ini', 'tgl_lomba' => '2026-05-10', 'lokasi' => 'Offline', 'link_daftar' => 'https://example.com/kaligrafi-modern', 'gambar' => 'uploads/1750083607_kaligrafi-modern.jpeg', 'penyelenggara_lomba' => 'Modern Calligraphy Society', 'updated_at' => $now, 'status' => 'available', 'id_bidang' => 12, 'kategori_peserta' => 'Umum', 'created_at' => $now],
            ['id_lomba' => 37, 'nama_lomba' => 'Lomba Menulis Novel', 'deskripsi' => 'Ciptakan novel terbaikmu dan menangkan hadiah menarik!', 'tgl_lomba' => '2026-05-20', 'lokasi' => 'Online', 'link_daftar' => 'https://example.com/menulis-novel', 'gambar' => 'uploads/1750083607_menulis-novel.jpeg', 'penyelenggara_lomba' => 'Novel Writing Community', 'updated_at' => $now, 'status' => 'available', 'id_bidang' => 17, 'kategori_peserta' => 'Umum', 'created_at' => $now],
            ['id_lomba' => 38, 'nama_lomba' => 'Lomba Desain Karakter', 'deskripsi' => 'Ciptakan karakter unik untuk game atau cerita dalam lomba ini', 'tgl_lomba' => '2026-06-10', 'lokasi' => 'Online', 'link_daftar' => 'https://example.com/desain-karakter', 'gambar' => 'uploads/1750083607_desain-karakter.jpeg', 'penyelenggara_lomba' => 'Character Design Society', 'updated_at' => $now, 'status' => 'available', 'id_bidang' => 18, 'kategori_peserta' => 'Umum', 'created_at' => $now],
            ['id_lomba' => 39, 'nama_lomba' => 'Lomba Animasi Pendek', 'deskripsi' => 'Buat animasi pendek kreatif dan menangkan hadiah menarik!', 'tgl_lomba' => '2026-06-20', 'lokasi' => 'Online', 'link_daftar' => 'https://example.com/animasi-pendek', 'gambar' => 'uploads/1750083607_animasi-pendek.jpeg', 'penyelenggara_lomba' => 'Animation Community', 'updated_at' => $now, 'status' => 'available', 'id_bidang' => 12, 'kategori_peserta' => 'Umum', 'created_at' => $now],
            ['id_lomba' => 40, 'nama_lomba' => 'Lomba Game Development', 'deskripsi' => 'Kembangkan game impianmu dan menangkan hadiah jutaan rupiah!', 'tgl_lomba' => '2026-07-10', 'lokasi' => 'Online', 'link_daftar' => 'https://example.com/game-development', 'gambar' => 'uploads/1750083607_game-development.jpeg', 'penyelenggara_lomba' => 'Game Dev Society', 'updated_at' => $now, 'status' => 'available', 'id_bidang' => 61, 'kategori_peserta' => 'Umum', 'created_at' => $now],
            ['id_lomba' => 41, 'nama_lomba' => 'Lomba Web Development', 'deskripsi' => 'Buat website kreatif dan fungsional dalam lomba bergengsi ini', 'tgl_lomba' => '2026-07-20', 'lokasi' => 'Online', 'link_daftar' => 'https://example.com/web-development', 'gambar' => 'uploads/1750083607_web-development.jpeg', 'penyelenggara_lomba' => 'Web Dev Community', 'updated_at' => $now, 'status' => 'available', 'id_bidang' => 24, 'kategori_peserta' => 'Umum', 'created_at' => $now],
            ['id_lomba' => 42, 'nama_lomba' => 'Lomba Aplikasi Mobile', 'deskripsi' => 'Kembangkan aplikasi mobile inovatif dan raih hadiah menarik!', 'tgl_lomba' => '2026-08-10', 'lokasi' => 'Online', 'link_daftar' => 'https://example.com/aplikasi-mobile', 'gambar' => 'uploads/1750083607_aplikasi-mobile.jpeg', 'penyelenggara_lomba' => 'Mobile App Community', 'updated_at' => $now, 'status' => 'available', 'id_bidang' => 11, 'kategori_peserta' => 'Umum', 'created_at' => $now],
            ['id_lomba' => 43, 'nama_lomba' => 'Lomba Internet of Things (IoT)', 'deskripsi' => 'Ciptakan solusi IoT terbaik dan menangkan hadiah bergengsi!', 'tgl_lomba' => '2026-08-20', 'lokasi' => 'Online', 'link_daftar' => 'https://example.com/iot', 'gambar' => 'uploads/1750083607_iot.jpeg', 'penyelenggara_lomba' => 'IoT Community', 'updated_at' => $now, 'status' => 'available', 'id_bidang' => 11, 'kategori_peserta' => 'Umum', 'created_at' => $now],
            ['id_lomba' => 44, 'nama_lomba' => 'Lomba Kecerdasan Buatan (AI)', 'deskripsi' => 'Kembangkan aplikasi AI inovatif dan raih prestasi bergengsi!', 'tgl_lomba' => '2026-09-10', 'lokasi' => 'Online', 'link_daftar' => 'https://example.com/ai', 'gambar' => 'uploads/1750083607_ai.jpeg', 'penyelenggara_lomba' => 'AI Community', 'updated_at' => $now, 'status' => 'available', 'id_bidang' => 62, 'kategori_peserta' => 'Umum', 'created_at' => $now],
            ['id_lomba' => 45, 'nama_lomba' => 'Lomba Blockchain', 'deskripsi' => 'Ciptakan solusi berbasis blockchain dan menangkan hadiah menarik!', 'tgl_lomba' => '2026-09-20', 'lokasi' => 'Online', 'link_daftar' => 'https://example.com/blockchain', 'gambar' => 'uploads/1750083607_blockchain.jpeg', 'penyelenggara_lomba' => 'Blockchain Community', 'updated_at' => $now, 'status' => 'available', 'id_bidang' => 11, 'kategori_peserta' => 'Umum', 'created_at' => $now],
            ['id_lomba' => 46, 'nama_lomba' => 'Lomba Cybersecurity', 'deskripsi' => 'Uji kemampuan cybersecurity mu dalam lomba bergengsi ini', 'tgl_lomba' => '2026-10-10', 'lokasi' => 'Online', 'link_daftar' => 'https://example.com/cybersecurity', 'gambar' => 'uploads/1750083607_cybersecurity.jpeg', 'penyelenggara_lomba' => 'Cybersecurity Community', 'updated_at' => $now, 'status' => 'available', 'id_bidang' => 64, 'kategori_peserta' => 'Umum', 'created_at' => $now],
            ['id_lomba' => 47, 'nama_lomba' => 'Lomba Data Science', 'deskripsi' => 'Tunjukkan kemampuan analisis datamu dalam lomba bergengsi ini', 'tgl_lomba' => '2026-10-20', 'lokasi' => 'Online', 'link_daftar' => 'https://example.com/data-science', 'gambar' => 'uploads/1750083607_data-science.jpeg', 'penyelenggara_lomba' => 'Data Science Community', 'updated_at' => $now, 'status' => 'available', 'id_bidang' => 11, 'kategori_peserta' => 'Umum', 'created_at' => $now],
            ['id_lomba' => 48, 'nama_lomba' => 'Cassevas Cup 7th', 'deskripsi' => 'Kompetisi multi-cabang terbesar dari SMAN 12 Jakarta dengan berbagai kategori lomba', 'tgl_lomba' => '2025-03-06', 'lokasi' => 'Online', 'link_daftar' => 'https://cassevas.dubes.my.id', 'gambar' => 'uploads/1750100943_cassevas-cup-7th-54.jpeg', 'penyelenggara_lomba' => 'SMAN 12 Jakarta', 'updated_at' => $now, 'status' => 'available', 'id_bidang' => 65, 'kategori_peserta' => 'Umum', 'created_at' => $now],
        ]);
    }
}